server:
  port: 8080
cors:
  originPatterns: >
    http://localhost:8080,
    https://localhost:3000,
    http://api.juniorapeles.xyz

spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rest_with_spring_boot_erudio
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      #show_sql: true
    open-in-view: false
logging:
  level:
    #root: WARN
    br.com.junior: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
